version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fraud_detection
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airbyte-worker:
    image: airbyte/worker
    environment:
      AIRBYTE_CONFIG_DIR: /tmp/airbyte_config
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  airflow-webserver:
    image: apache/airflow:2.7.2
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:password@postgres:5432/fraud_detection
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.0
    environment:
      DBT_PROFILES_DIR: /usr/app/dbt
    volumes:
      - ./dbt:/usr/app/dbt
    depends_on:
      - postgres

  soda:
    image: sodadata/soda-core
    volumes:
      - ./soda:/app/soda
    depends_on:
      - postgres

volumes:
  postgres_data:


